import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: ["192.168.56.1"],
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: "media.articog.com" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "img.youtube.com" },
      { protocol: "https", hostname: "i.ytimg.com" },
      { protocol: "https", hostname: "miro.medium.com" },
    ],
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              "base-uri 'self'",
              "frame-ancestors 'self'",
              "object-src 'none'",
              "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://assets.calendly.com https://articog.breezy.hr https://subscribe-forms.beehiiv.com",
              "style-src 'self' 'unsafe-inline' https://assets.calendly.com",
              "font-src 'self' data:",
              "img-src 'self' data: blob: https://res.cloudinary.com https://media.articog.com https://images.unsplash.com https://img.youtube.com https://miro.medium.com",
              "media-src 'self' https://res.cloudinary.com https://media.articog.com",
              "connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://api.resend.com https://*.googleapis.com https://articog.breezy.hr https://calendly.com https://*.calendly.com https://assets.calendly.com",
              "frame-src 'self' https://calendly.com https://*.calendly.com https://www.youtube.com https://www.youtube-nocookie.com",
              "form-action 'self'",
            ].join("; "),
          },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Strict-Transport-Security", value: "max-age=31536000; includeSubDomains" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
  async redirects() {
    return [
      { source: "/why-articog/production-economics", destination: "/why-articog#production-economics", statusCode: 301 },
      { source: "/how-it-works", destination: "/why-articog#how-it-works", statusCode: 301 },
      { source: "/trust", destination: "/why-articog#trust", statusCode: 301 },
      { source: "/services/ai-video-production/automotive", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/brand-films", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/corporate-internal", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/localization", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/performance-ads", destination: "/services/ad-creative", statusCode: 301 },
      { source: "/services/ai-video-production/product-commercials", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/product-launch", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/real-estate", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/saas-explainers", destination: "/services/ai-video-production", statusCode: 301 },
      { source: "/services/ai-video-production/social-reels", destination: "/services/social-creative", statusCode: 301 },
      { source: "/services/ai-video-production/ugc-style-ads", destination: "/services/ad-creative", statusCode: 301 },
      { source: "/services/ad-creative/key-visuals", destination: "/services/ad-creative", statusCode: 301 },
      { source: "/services/ad-creative/static-ads", destination: "/services/ad-creative", statusCode: 301 },
      { source: "/services/ad-creative/testing-variants", destination: "/services/ad-creative", statusCode: 301 },
      { source: "/services/audio/ai-voiceover", destination: "/services/audio", statusCode: 301 },
      { source: "/services/audio/audio-ads", destination: "/services/audio", statusCode: 301 },
      { source: "/services/audio/music-sound-design", destination: "/services/audio", statusCode: 301 },
      { source: "/services/creative-strategy/campaigns", destination: "/services/creative-strategy", statusCode: 301 },
      { source: "/services/creative-strategy/concept-development", destination: "/services/creative-strategy", statusCode: 301 },
      { source: "/services/creative-strategy/storyboarding", destination: "/services/creative-strategy", statusCode: 301 },
      { source: "/services/post-production/ai-compositing", destination: "/services/post-production", statusCode: 301 },
      { source: "/services/post-production/mastering", destination: "/services/post-production", statusCode: 301 },
      { source: "/services/post-production/motion-graphics", destination: "/services/post-production", statusCode: 301 },
      { source: "/services/post-production/video-editing", destination: "/services/post-production", statusCode: 301 },
      { source: "/services/product-visuals/ecommerce", destination: "/services/product-visuals", statusCode: 301 },
      { source: "/services/product-visuals/image-libraries", destination: "/services/product-visuals", statusCode: 301 },
      { source: "/services/product-visuals/product-photography", destination: "/services/product-visuals", statusCode: 301 },
      { source: "/services/social-creative/monthly-content", destination: "/services/social-creative", statusCode: 301 },
      { source: "/services/social-creative/repurposing", destination: "/services/social-creative", statusCode: 301 },
      { source: "/services/brand-films", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/product-commercials", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/performance-ads", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/social-reel-production", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/product-launch-videos", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/localization-variants", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/commercials", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/product-films", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/explainers", destination: "/services/ai-video-production", permanent: true },
      { source: "/services/performance-video-ads", destination: "/services/ad-creative", permanent: true },
      { source: "/services/testing-variants", destination: "/services/ad-creative", permanent: true },
      { source: "/services/campaign-key-visuals", destination: "/services/ad-creative", permanent: true },
      { source: "/services/paid-ads", destination: "/services/ad-creative", permanent: true },
      { source: "/services/ugc-style-creative", destination: "/services/ad-creative", permanent: true },
      { source: "/services/reels-short-form", destination: "/services/ad-creative", permanent: true },
      { source: "/services/creative-variants", destination: "/services/ad-creative", permanent: true },
      { source: "/services/monthly-social-content", destination: "/services/social-creative", permanent: true },
      { source: "/services/creative-repurposing", destination: "/services/social-creative", permanent: true },
      { source: "/services/social-assets", destination: "/services/social-creative", permanent: true },
      { source: "/services/product-visual-content", destination: "/services/product-visuals", permanent: true },
      { source: "/services/ai-product-photography", destination: "/services/product-visuals", permanent: true },
      { source: "/services/custom-image-libraries", destination: "/services/product-visuals", permanent: true },
      { source: "/services/ecommerce-visuals", destination: "/services/product-visuals", permanent: true },
      { source: "/services/campaign-imagery", destination: "/services/product-visuals", permanent: true },
      { source: "/services/ooh-display", destination: "/services/product-visuals", permanent: true },
      { source: "/services/ai-voiceover", destination: "/services/audio", permanent: true },
      { source: "/services/music-sound-design", destination: "/services/audio", permanent: true },
      { source: "/services/campaign-strategy", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/concept-development", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/storyboarding-previs", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/creative-automation", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/multi-format-adaptation", destination: "/services/creative-strategy", permanent: true },
      { source: "/services/ai-post-production", destination: "/services/post-production", permanent: true },
      { source: "/services/motion-graphics", destination: "/services/post-production", permanent: true },
      { source: "/services/upscaling-mastering", destination: "/services/post-production", permanent: true },
      { source: "/services/ai-compositing", destination: "/services/post-production", permanent: true },
      { source: "/services/video-editing", destination: "/services/post-production", permanent: true },
      { source: "/solutions/creative-testing", destination: "/solutions/performance-marketing", statusCode: 301 },
      { source: "/solutions/multi-format-campaigns", destination: "/solutions/product-launch", statusCode: 301 },
      { source: "/solutions/always-on-content", destination: "/solutions/monthly-creative-subscription", statusCode: 301 },
      { source: "/solutions/agency-white-label", destination: "/solutions/creative-team-overflow", statusCode: 301 },
      { source: "/solutions/localization-global", destination: "/solutions/product-launch", statusCode: 301 },
      { source: "/solutions/creative-automation", destination: "/solutions/performance-marketing", statusCode: 301 },
      { source: "/solutions/dynamic-creative", destination: "/solutions/performance-marketing", statusCode: 301 },
      { source: "/solutions/performance-testing", destination: "/solutions/performance-marketing", statusCode: 301 },
      { source: "/solutions/paid-social-scale", destination: "/solutions/performance-marketing", statusCode: 301 },
      { source: "/solutions/ugc-style-content", destination: "/solutions/performance-marketing", statusCode: 301 },
      { source: "/solutions/brand-films-cinematic", destination: "/solutions/product-launch", statusCode: 301 },
      { source: "/solutions/audio-ads-streaming", destination: "/solutions/product-launch", statusCode: 301 },
      { source: "/solutions/by-industry/consumer-goods", destination: "/industries", statusCode: 301 },
      { source: "/solutions/by-industry/gaming-apps", destination: "/industries", statusCode: 301 },
      { source: "/solutions/by-industry/luxury-fashion", destination: "/industries", statusCode: 301 },
      { source: "/solutions/by-industry/travel-hospitality", destination: "/industries", statusCode: 301 },
      { source: "/industries/automotive-mobility", destination: "/industries", statusCode: 301 },
      { source: "/industries/beauty-skincare", destination: "/industries", statusCode: 301 },
      { source: "/industries/consumer-electronics", destination: "/industries", statusCode: 301 },
      { source: "/industries/dtc-ecommerce", destination: "/industries", statusCode: 301 },
      { source: "/industries/fashion-lifestyle", destination: "/industries", statusCode: 301 },
      { source: "/industries/food-beverage", destination: "/industries", statusCode: 301 },
      { source: "/industries/real-estate", destination: "/industries", statusCode: 301 },
      { source: "/industries/saas-technology", destination: "/industries", statusCode: 301 },
      { source: "/community/afin", destination: "/about", statusCode: 301 },
      { source: "/trust/responsible-ai", destination: "/trust/ai-and-ip", statusCode: 301 },
      { source: "/privacy", destination: "/privacy-policy", statusCode: 301 },
      { source: "/legal/privacy-policy", destination: "/privacy-policy", statusCode: 301 },
      { source: "/accessibility", destination: "/legal/accessibility", statusCode: 301 },
      { source: "/legal/dpa", destination: "/contact", statusCode: 301 },
      { source: "/legal/msa", destination: "/contact", statusCode: 301 },
      { source: "/legal/subprocessors", destination: "/contact", statusCode: 301 },
      { source: "/how-it-works/onboarding", destination: "/how-it-works", statusCode: 301 },
      { source: "/how-it-works/quality-assurance", destination: "/how-it-works/ai-creative-pipeline", statusCode: 301 },
      { source: "/how-it-works/revisions-delivery", destination: "/how-it-works", statusCode: 301 },
      { source: "/pricing/monthly-plans", destination: "/pricing", statusCode: 301 },
      { source: "/pricing/pilot", destination: "/pricing", statusCode: 301 },
      { source: "/resources", destination: "/blog", statusCode: 301 },
      { source: "/guides", destination: "/blog", statusCode: 301 },
      { source: "/playbooks", destination: "/blog", statusCode: 301 },
      { source: "/reports", destination: "/blog", statusCode: 301 },
      { source: "/events", destination: "/blog", statusCode: 301 },
      { source: "/glossary", destination: "/help", statusCode: 301 },
      { source: "/compare/traditional-production", destination: "/compare/vs-traditional-production", statusCode: 301 },
      { source: "/compare/ai-tools", destination: "/compare/vs-ai-tools", statusCode: 301 },
      { source: "/compare/agencies", destination: "/compare/vs-traditional-production", statusCode: 301 },
      { source: "/compare/freelancers", destination: "/compare/vs-traditional-production", statusCode: 301 },
    ];
  },
};

export default nextConfig;